/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module dual_port_ram(clk_a, clk_b, write_enable_a, write_enable_b, output_enable_a, output_enable_b, address_a, address_b, data_in_a, data_in_b, data_out_a, data_out_b, collision);
  input clk_a;
  wire clk_a;
  input clk_b;
  wire clk_b;
  input write_enable_a;
  wire write_enable_a;
  input write_enable_b;
  wire write_enable_b;
  input output_enable_a;
  wire output_enable_a;
  input output_enable_b;
  wire output_enable_b;
  input [7:0] address_a;
  wire [7:0] address_a;
  input [7:0] address_b;
  wire [7:0] address_b;
  input [7:0] data_in_a;
  wire [7:0] data_in_a;
  input [7:0] data_in_b;
  wire [7:0] data_in_b;
  output [7:0] data_out_a;
  wire [7:0] data_out_a;
  output [7:0] data_out_b;
  wire [7:0] data_out_b;
  output collision;
  wire collision;
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  reg [7:0] memory [255:0];
  always @(posedge clk_b) begin
    if (_00_[0])
      memory[address_b] <= data_in_b;
  end
  always @(posedge clk_a) begin
    if (write_enable_a)
      memory[address_a] <= data_in_a;
  end
  reg [7:0] _51_;
  reg [7:0] _52_;
  always @(posedge clk_b) begin
    if (_02_)
      _52_ <= 8'h00;
    else begin
      _52_ <= memory[address_b];
    end
  end
  always @(posedge clk_a) begin
    if (_01_)
      _51_ <= 8'h00;
    else begin
      _51_ <= memory[address_a];
    end
  end
  assign data_out_a = _51_;
  assign data_out_b = _52_;
  assign _02_ = ~output_enable_b;
  assign _01_ = ~output_enable_a;
  assign _03_ = write_enable_b & write_enable_a;
  assign _04_ = address_a[5] | ~(address_b[5]);
  assign _05_ = ~(address_a[2] ^ address_b[2]);
  assign _06_ = address_b[5] | ~(address_a[5]);
  assign _07_ = address_b[1] | ~(address_a[1]);
  assign _08_ = address_a[1] | ~(address_b[1]);
  assign _09_ = ~(address_a[6] ^ address_b[6]);
  assign _10_ = address_a[0] | ~(address_b[0]);
  assign _11_ = address_b[0] | ~(address_a[0]);
  assign _12_ = ~(address_a[3] ^ address_b[3]);
  assign _13_ = ~(address_a[7] ^ address_b[7]);
  assign _14_ = _12_ & _13_;
  assign _15_ = ~(address_a[4] ^ address_b[4]);
  assign _16_ = _05_ & _15_;
  assign _17_ = _09_ & _16_;
  assign _18_ = _06_ & _07_;
  assign _19_ = _08_ & _18_;
  assign _20_ = _04_ & _11_;
  assign _21_ = _03_ & _10_;
  assign _22_ = _20_ & _21_;
  assign _23_ = _19_ & _22_;
  assign _24_ = _17_ & _23_;
  assign collision = _14_ & _24_;
  assign _00_[0] = write_enable_b & ~(collision);
  assign _00_[7:1] = { _00_[0], _00_[0], _00_[0], _00_[0], _00_[0], _00_[0], _00_[0] };
endmodule
